SELECT
EEC.`CODE`,
UPPER(EEC.U_EMPLOYEE_EMERGENCY_CONTACT_NAME) AS "eec_contact_name",
EEC.U_EMPLOYEE_EMERGENCY_CONTACT_RELATIONSHIP AS "eec_relationship",
EEC.U_EMPLOYEE_EMERGENCY_CONTACT_MOBILE AS "eec_mobile",
EEC.U_EMPLOYEE_EMERGENCY_CONTACT_WORK_TELEPHONE AS "eec_work_telephone",
EEC.U_EMPLOYEE_EMERGENCY_CONTACT_HOME_TELEPHONE AS "eec_home_telephone"
FROM 
u_employee_details AS ED
LEFT JOIN u_employee_emergency_contacts AS EEC ON ED.`CODE` = EEC.`CODE`
WHERE ED.`code` = "C-100002"