SELECT
EEB.`CODE`,
EEB.U_EMPLOYEE_EDUCATIONAL_BACKGROUND_LEVEL AS "background_level",
EEB.U_EMPLOYEE_EDUCATIONAL_BACKGROUND_SCHOOL_NAME AS "school",
EEB.U_EMPLOYEE_EDUCATIONAL_BACKGROUND_DEGREE_COURSE AS "program",
CAST(YEAR(EEB.U_EMPLOYEE_EDUCATIONAL_BACKGROUND_START_DATE) AS char) AS "date_start",
CAST(YEAR(EEB.U_EMPLOYEE_EDUCATIONAL_BACKGROUND_START_DATE) AS char) AS "date_start",
EEB.U_EMPLOYEE_EDUCATIONAL_BACKGROUND_ACAD_HONORS AS "honors"
FROM
U_EMPLOYEE_DETAILS AS ED
RIGHT JOIN u_employee_educational_background AS EEB ON ED.`CODE` = EEB.`CODE`