SELECT 
EWE.`CODE`,
EWE.U_EMPLOYEE_WORK_EXPERIENCE_COMPANY AS "ewe_company",
EWE.U_EMPLOYEE_WORK_EXPERIENCE_POSITION AS "ewe_position",
EWE.U_EMPLOYEE_WORK_EXPERIENCE_APPOINTMENT_STATUS AS "ewe_apointment_status",
EWE.U_EMPLOYEE_WORK_EXPERIENCE_DATE_FROM AS "ewe_date_from",
EWE.U_EMPLOYEE_WORK_EXPERIENCE_DATE_TO AS "ewe_date_to"
FROM u_employee_details AS ED
LEFT JOIN u_employee_work_experience AS EWE ON ED.`CODE` = EWE.`CODE`
WHERE 
EWE.U_EMPLOYEE_WORK_EXPERIENCE_COMPANY <> ""
AND ED.`CODE` = "C-100002"