SELECT DISTINCT
EJ.U_EMPLOYEE_EMPLOYMENT_JOB_CATEGORY AS job_category,
(
	SELECT COUNT(U_EMPLOYEE_JOB.`CODE`) 
	FROM U_EMPLOYEE_JOB 
	WHERE U_EMPLOYEE_JOB.U_EMPLOYEE_EMPLOYMENT_JOB_CATEGORY = job_category
) AS job_population
FROM 
U_EMPLOYEE_JOB AS EJ
WHERE EJ.U_EMPLOYEE_EMPLOYMENT_JOB_CATEGORY <> ""